# constants.py

# Default times
DEFAULT_START_TIME_OF_DAY = "09:00"
DEFAULT_LUNCH_TIME = "12:30"
DEFAULT_DINNER_TIME = "18:00"
DEFAULT_DAY_END_TIME = "21:00"

# Default durations (minutes)
DEFAULT_POI_DURATION = 90
DEFAULT_TRANSPORT_TIME_CAR = 20
DEFAULT_TRANSPORT_TIME_NO_CAR = 45
DEFAULT_FLEXIBLE_BLOCK = 60

# Meal durations
BREAKFAST_DURATION = 30
LUNCH_DURATION = 60
DINNER_DURATION = 60

# Default fallback transport minutes if Directions API fails
FALLBACK_TRANSPORT_MINUTES_CAR = 10
FALLBACK_TRANSPORT_MINUTES_NO_CAR = 15

# Transportation modes
TRANSPORT_MODE_HAVE_CAR = "have_car"
TRANSPORT_MODE_NO_CAR = "no_car"
